{
 "title": "Custom Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "coin",
    "label": "Cryptocurrency",
    "query": {
     "query": "label_values(crypto_price_usd,coin)"
    }
   },
   {
    "name": "query0",
    "query": {
     "query": "label_values(crypto_price_usd,category)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Исторический контекст минимумов криптовалюты ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(crypto_atl_usd{coin=~\"$coin\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Относительная волатильность (high-low)/price",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "crypto_high_24h_usd{category=\"$query0\"} - crypto_low_24h_usd / crypto_price_usd",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимальная капитализация по категориям.",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(category) (crypto_market_cap_usd{category=\"$query0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Скорость изменений объема торгов за минуту.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(crypto_volume_changes_total{category=\"$query0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущая цена Bitcoin в USD.",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "crypto_price_usd{coin=\"bitcoin\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "crypto_price_usd{coin=\"bitcoin\"} offset $__interval",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(crypto_price_usd{coin=\"bitcoin\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "min_over_time(crypto_price_usd{coin=\"bitcoin\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Суммарная цена по категориям (top/alt coins)",
   "type": "piechart",
   "description": "Сравнивает группы монет.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (category) (crypto_price_usd)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущая цена Ethereum в USD",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "crypto_price_usd{coin=\"ethereum\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "crypto_price_usd{coin=\"ethereum\"} offset $__interval",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(crypto_price_usd{coin=\"ethereum\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "min_over_time(crypto_price_usd{coin=\"ethereum\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Рыночная капитализация Bitcoin и Ethereum",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_market_cap_usd{coin=\"bitcoin\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "crypto_market_cap_usd{coin=\"ethereum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Объем торгов Ethereum и Bitcoin за 24 часа в USD.",
   "type": "timeseries",
   "description": "Отражает ликвидность",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "crypto_volume_24h_usd{category=\"$query0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Минимальная цена криптовалюты 24 часа в USD.",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_low_24h_usd{coin=\"$coin\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}