{
 "title": "Database Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query0",
    "label": "Название ",
    "query": {
     "query": "label_values(pg_database_size_bytes,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Общий размер базы данных в байтах и ГБ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{datname=\"$query0\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(pg_database_size_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время работы экспортера в секундах.",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"postgres_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Скорость коммитов и роллбэков транзакций за минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"$query0\"}[1m]) + (rate(pg_stat_database_xact_rollback{datname=\"$query0\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "количество мертвых строк и живых строк",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(pg_stat_user_tables_n_live_tup{datname=\"$query0\"}), \"type\", \"Live Tuples\", \"\", \"\") or (label_replace(sum(pg_stat_user_tables_n_dead_tup{datname=\"$query0\"}), \"type\", \"Dead Tuples\", \"\", \"\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество таблиц с живыми строками",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_user_tables_n_live_tup{datname=\"$query0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее количество живых и мертвых строк в пользовательских таблицах",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_n_live_tup + pg_stat_user_tables_n_dead_tup)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Суммарное количество активных подключений к базе.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"$query0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Суммарное количество конфликтов в базе данных",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_conflicts{datname=\"$query0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество ролей с установленными лимитами подключений",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_roles_connection_limit)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Скорость операций вставки, обновления и удаления строк в базе данных за минуту.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_tup_inserted{datname=\"$query0\"}[1m]) + rate(pg_stat_database_tup_updated{datname=\"$query0\"}[1m]) + rate(pg_stat_database_tup_deleted{datname=\"$query0\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее количество \"мертвых\" строк в таблицах базы данных",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_n_dead_tup{datname=\"$query0\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}